# Generated by Django 3.1.7 on 2021-03-12 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
                ('bid', models.IntegerField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('uid', models.IntegerField(max_length=100)),
                ('title', models.CharField(max_length=225)),
                ('date', models.DateTimeField(verbose_name=datetime.datetime(2021, 3, 12, 4, 38, 29, 100251))),
                ('style', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='column',
            fields=[
                ('cid', models.IntegerField(max_length=120000, primary_key=True, serialize=False, unique=True)),
                ('bid', models.IntegerField(max_length=200)),
                ('name', models.CharField(max_length=125)),
                ('date', models.DateTimeField(verbose_name=datetime.datetime(2021, 3, 12, 4, 38, 29, 101602))),
                ('position', models.IntegerField(max_length=600)),
                ('style', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('tid', models.IntegerField(max_length=1000, primary_key=True, serialize=False, unique=True)),
                ('cid', models.IntegerField(max_length=120000)),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=750)),
                ('priority', models.IntegerField(max_length=5)),
                ('progress', models.IntegerField(max_length=100)),
                ('date', models.DateTimeField(verbose_name=datetime.datetime(2021, 3, 12, 4, 38, 29, 102745))),
                ('position', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('uid', models.IntegerField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=85)),
                ('passlock', models.CharField(max_length=255)),
            ],
        ),
    ]
